usuarios:
    resource: "@usuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios

tapas:
    resource: "@tapasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
